CREATE TABLE books (
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Genre VARCHAR(255) NOT NULL,
    PublicationDate DATE NOT NULL,
    Publisher VARCHAR(255) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL
);
