CREATE TABLE Purchases (
  PurchaseID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  BookID INT UNSIGNED NOT NULL,
  CustomerID INT UNSIGNED NOT NULL,
  OrderDate DATE NOT NULL,
  PRIMARY KEY (PurchaseID),
  FOREIGN KEY (BookID) REFERENCES Books(BookID),
  FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
) ENGINE=InnoDB;

INSERT INTO Purchases (BookID, CustomerID, OrderDate)
VALUES (1, 1, '2022-01-01'),
       (2, 2, '2022-01-02');
